// packages/client/src/lib/workspace/Workspace.svelte
<script lang="ts">
    import { Portal } from "@ark-ui/svelte/portal";
    import { Tooltip } from "@ark-ui/svelte/tooltip";
    import { onMount, type Snippet } from "svelte";
    import type { ActiveSlideStore } from "$lib/active-slide/active-slide-store.svelte";
    import { countNoteGroups } from "$lib/outliner/count-groups";
    import { m } from "$lib/paraglide/messages";
    import SlideList from "$lib/slide-list/SlideList.svelte";
    import { computeSlideOverflow } from "$lib/slide-overflow";
    import SlideListErrorOverlay from "$lib/slide-status/SlideListErrorOverlay.svelte";
    import SlideListHint from "$lib/slide-status/SlideListHint.svelte";
    import type { SlidesMetaStore } from "$lib/slides-meta/slides-meta-store.svelte";
    import { SyncPublisher } from "$lib/sync/sync-publisher";
    import { ThemeStore } from "$lib/theme/theme-store.svelte";
    import PlayIcon from "phosphor-svelte/lib/PlayIcon";
    import SidebarSimpleIcon from "phosphor-svelte/lib/SidebarSimpleIcon";

    const LIST_OPEN_KEY = "nfp:listOpen";

    interface Props {
        docTitle: string;
        outline: unknown;
        ready: boolean;
        loadFailed?: boolean;
        meta: SlidesMetaStore;
        active: ActiveSlideStore;
        titleArea: Snippet;
        outliner: Snippet;
    }

    const {
        docTitle,
        outline,
        ready,
        loadFailed = false,
        meta,
        active,
        titleArea,
        outliner,
    }: Props = $props();

    const theme = new ThemeStore();
    const publisher = new SyncPublisher();

    let listOpen: boolean = $state(true);

    const groupCount = $derived(countNoteGroups(outline));
    const pdfCount = $derived(
        meta.data?.kind === "resolved" ? meta.data.pageCount : 0,
    );
    const overflow = $derived(computeSlideOverflow(pdfCount, groupCount));
    // Read through a scalar derived so the publish effect below only re-runs when
    // the count itself changes — `overflow` is a fresh object on every recompute.
    const slideCount = $derived(overflow.slideCount);
    // Slide aspect ratio (width / height) from the actual PDF, falling back to 16:9
    // until the resolved meta provides real page dimensions. Drives --scroll-tail and
    // the overflow placeholders.
    const slideAspect = $derived(
        meta.data?.kind === "resolved" && meta.data.width && meta.data.height
            ? meta.data.width / meta.data.height
            : 16 / 9,
    );

    onMount(() => {
        theme.hydrate();
        active.hydrate();
        listOpen = (localStorage.getItem(LIST_OPEN_KEY) ?? "true") === "true";
        return () => {
            publisher.destroy();
        };
    });

    $effect(() => {
        theme.persist();
        theme.applyToDocument();
    });

    $effect(() => {
        localStorage.setItem(LIST_OPEN_KEY, String(listOpen));
    });

    $effect(() => {
        active.syncToUrl();
    });

    $effect(() => {
        publisher.publishActiveSlide(active.value);
    });

    $effect(() => {
        publisher.publishPageCount(slideCount);
    });

    function onSelectFromList(n: number) {
        active.set(n);
    }
</script>

<svelte:head>
    <title>{m.page_title({ title: docTitle })}</title>
</svelte:head>

<!--
  --scroll-tail: trailing scroll space below the slide list and the outliner so the
  last slide (or note group) can be scrolled to the top — one panel height minus one
  slide's height (a thumbnail spanning the panel: 100cqw / aspect, plus a tuned +19.5px
  for fixed item chrome), minus the slide list's scroll-padding-top (scroll-p-1 =
  0.25rem) so the last slide rests where an active slide scrolls to. Clamped to >= 0 for
  portrait decks where a thumbnail is taller than the panel. Both panels use this same
  value so their bottom spacing matches. Resolves per scroll container via container-
  query units; the panels set `container-type: size`.
-->
<div
    class={[
        "grid h-svh grid-rows-[auto_1fr_auto]",
        listOpen ? "grid-cols-2" : "grid-cols-1",
        "[--scroll-tail:max(0px,calc(100cqh_-_100cqw/var(--slide-aspect)_+_19.5px_-_0.25rem))]",
    ]}
    style="--slide-aspect: {slideAspect}"
>
    <div
        class="col-span-full py-1 flex flex-wrap items-center gap-3 border-b border-gray-200 bg-gray-50 px-4"
    >
        {@render titleArea()}
        <Tooltip.Root interactive>
            <Tooltip.Trigger>
                {#snippet asChild(props)}
                    <a
                        {...props({
                            class: "text-sm text-gray-800 min-w-8 min-h-7 flex items-center justify-center hover:bg-gray-200 transition duration-100 rounded",
                            "aria-label": m.open_slideshow(),
                        })}
                        href={`/slideshow?slide=${active.value}`}
                        target="nfp-slideshow"
                    >
                        <PlayIcon size="1.25em" weight="duotone" />
                    </a>
                {/snippet}
            </Tooltip.Trigger>
            {@render tip(m.open_slideshow())}
        </Tooltip.Root>
        <Tooltip.Root interactive>
            <Tooltip.Trigger>
                {#snippet asChild(props)}
                    <button
                        {...props({
                            type: "button",
                            class: "min-w-8 min-h-7 text-sm text-gray-800 flex items-center justify-center hover:bg-gray-200 transition duration-100 rounded",
                            onclick: () => (listOpen = !listOpen),
                            "aria-expanded": listOpen,
                            "aria-label": m.toggle_slide_list(),
                        })}
                    >
                        <SidebarSimpleIcon
                            size="1.25em"
                            weight={listOpen ? "duotone" : "regular"}
                            mirrored
                        />
                    </button>
                {/snippet}
            </Tooltip.Trigger>
            {@render tip(m.toggle_slide_list())}
        </Tooltip.Root>
    </div>

    <div
        class="relative overflow-auto overscroll-none scroll-pt-4 [container-type:size]"
    >
        {#if loadFailed}
            <SlideListErrorOverlay message={m.load_error()} />
        {:else if ready}
            {@render outliner()}
        {/if}
    </div>

    {#if listOpen}
        <div
            class="overflow-y-auto overscroll-none border-l border-gray-200 bg-gray-50 p-1 scroll-p-1 [container-type:size]"
        >
            {#if !ready}
                <SlideListHint message="…" />
            {:else if meta.data?.kind === "resolved"}
                <SlideList
                    hash={meta.data.hash}
                    pageCount={slideCount}
                    overflowStart={overflow.overflowStart}
                    activeSlide={active.value}
                    onSelect={onSelectFromList}
                />
            {:else if meta.data?.kind === "no-config-no-file"}
                <SlideListHint message={m.info_no_slides()} />
            {:else if meta.data?.kind === "configured-but-missing"}
                <SlideListErrorOverlay
                    message={m.error_slides_not_found({
                        path: meta.data.configuredPath,
                    })}
                />
            {:else if meta.data?.kind === "no-config-multiple-files"}
                <SlideListErrorOverlay
                    message={m.error_multiple_pdfs({
                        files: meta.data.candidates.join(", "),
                    })}
                />
            {:else if meta.error}
                <SlideListErrorOverlay message={meta.error} />
            {/if}
        </div>
    {/if}

    <div
        class="col-span-full flex border-t border-gray-200 bg-gray-50 px-4 py-1"
    >
        <fieldset
            role="radiogroup"
            aria-label={m.theme_label()}
            class="flex gap-3 ml-auto"
        >
            <label
                class="flex items-center gap-1 p-1 -mx-1 text-gray-800 text-sm"
                ><input
                    type="radio"
                    name="theme"
                    bind:group={theme.mode}
                    value="system"
                />
                {m.theme_system()}</label
            >
            <label
                class="flex items-center gap-1 p-1 -mx-1 text-gray-800 text-sm"
                ><input
                    type="radio"
                    name="theme"
                    bind:group={theme.mode}
                    value="light"
                />
                {m.theme_light()}</label
            >
            <label
                class="flex items-center gap-1 p-1 -mx-1 text-gray-800 text-sm"
                ><input
                    type="radio"
                    name="theme"
                    bind:group={theme.mode}
                    value="dark"
                />
                {m.theme_dark()}</label
            >
        </fieldset>
    </div>
</div>

{#snippet tip(text: string)}
    <Portal>
        <Tooltip.Positioner>
            <Tooltip.Content
                class="rounded bg-gray-900 px-2 py-1 text-xs text-gray-50 shadow [--arrow-background:var(--color-gray-900)] [--arrow-size:8px]"
            >
                <Tooltip.Arrow>
                    <Tooltip.ArrowTip />
                </Tooltip.Arrow>
                {text}
            </Tooltip.Content>
        </Tooltip.Positioner>
    </Portal>
{/snippet}

// packages/client/src/components/workspace/Workspace.tsx
import { PlayIcon } from '@phosphor-icons/react/dist/csr/Play';
import { SidebarSimpleIcon } from '@phosphor-icons/react/dist/csr/SidebarSimple';
import clsx from 'clsx';
import { useEffect, type CSSProperties, type ReactNode } from 'react';
import { Button, Link, Radio, RadioGroup, TooltipTrigger } from 'react-aria-components';
import { m } from '../../lib/paraglide/messages.js';
import { ErrorOverlay } from '../ErrorOverlay';
import { Hint } from '../Hint';
import { computeSlideOverflow } from '../slides/overflow';
import { SlideList } from '../slides/SlideList';
import { describeSlidesMeta, type SlidesMeta } from '../slides/slidesMeta';
import { useSyncPublisher } from '../slides/sync';
import { Tooltip } from '../Tooltip';
import type { Resource, ResourceStatus } from '../useResource';
import { useListOpen } from './listOpen';
import { useTheme, type ThemeMode } from './theme';

export interface WorkspaceProps {
  /** The presentation's title, for the browser tab. Already defaulted by the caller. */
  title: string;
  /**
   * Note groups in the outline. Half of the deck's length — the other half is
   * the PDF's page count — and deliberately not the outline itself: this number
   * only moves when a `---` is added or removed, so the slide list is spared a
   * re-render per keystroke (plans/react-rewrite-spec.md §3.6).
   */
  groupCount: number;
  /** Where the stored document has got to. The outliner and the list wait on it. */
  status: ResourceStatus;
  meta: Resource<SlidesMeta>;
  activeSlide: number;
  onActiveSlideChange: (slide: number) => void;
  /**
   * The toolbar's leading area: an editable field in the Editor, a heading in
   * the Viewer. A `ReactNode` rather than a render prop — the shell has nothing
   * to hand back (§3.3).
   */
  titleArea: ReactNode;
  /** The outline editor, or nothing while the document is still loading (§4.4). */
  outliner: ReactNode;
}

// The label is the message function itself rather than a key to look up: a
// dynamic `m[someKey]()` would defeat the tree-shaking that is the point of
// compiling messages.
const THEME_OPTIONS: {
  mode: ThemeMode;
  label: () => string;
}[] = [
  { mode: 'system', label: m.theme_option_system },
  { mode: 'light', label: m.theme_option_light },
  { mode: 'dark', label: m.theme_option_dark },
];

const TOOLBAR_BUTTON =
  'flex min-h-7 min-w-8 items-center justify-center rounded text-sm text-gray-800 transition duration-100 hover:bg-gray-200';

/**
 * The workspace shell: toolbar, outliner panel, slide list, theme footer.
 *
 * Everything it owns is something that stops here — the colour scheme, whether
 * the list is showing, and the broadcast the slideshow window follows. Anything
 * two pages need is owned by the page above and arrives as a prop, so there is
 * no context anywhere in the tree (§3.3).
 *
 * It broadcasts rather than owns `activeSlide`: publishing needs the effective
 * slide count, and this is the one component holding both halves of it.
 */
export function Workspace({
  title,
  groupCount,
  status,
  meta,
  activeSlide,
  onActiveSlideChange,
  titleArea,
  outliner,
}: WorkspaceProps) {
  const [theme, setTheme] = useTheme();
  const [listOpen, setListOpen] = useListOpen();

  const resolved = meta.data?.kind === 'resolved' ? meta.data : null;
  const overflow = computeSlideOverflow(resolved?.pageCount ?? 0, groupCount);
  // The deck's real aspect ratio once the meta lands, 16:9 until then. Drives
  // both the overflow placeholders and --scroll-tail below.
  const slideAspect =
    resolved?.width && resolved.height ? resolved.width / resolved.height : 16 / 9;

  useSyncPublisher(activeSlide, overflow.slideCount);

  const pageTitle = m.browser_tab_title({ title });
  useEffect(() => {
    document.title = pageTitle;
  }, [pageTitle]);

  function slidePanel(): ReactNode {
    // Neither half of the deck's length is known yet: the note-group count comes
    // from the document, the page count from the metadata. Waiting on both is
    // what puts the ellipsis here rather than an empty panel — `describeSlidesMeta`
    // says nothing while a request is still in flight, by design.
    if (status !== 'ready' || meta.status === 'loading') return <Hint message="…" />;
    if (resolved) {
      return (
        <SlideList
          hash={resolved.hash}
          overflow={overflow}
          activeSlide={activeSlide}
          onActiveSlideChange={onActiveSlideChange}
        />
      );
    }
    // Every other shape the server can answer with is a sentence to show rather
    // than a deck to draw. The slideshow page shows the same sentences.
    const state = describeSlidesMeta(meta.data, meta.error);
    if (!state) return null;
    return state.tone === 'hint' ? (
      <Hint message={state.message} />
    ) : (
      <ErrorOverlay message={state.message} />
    );
  }

  return (
    // --scroll-tail: trailing scroll space below the slide list and the outliner so
    // the last slide (or note group) can be scrolled to the top — one panel height
    // minus one slide's height (a thumbnail spanning the panel: 100cqw / aspect, plus
    // a tuned +19.5px for fixed item chrome), minus the slide list's scroll-padding-top
    // (scroll-p-1 = 0.25rem) so the last slide rests where an active slide scrolls to.
    // Clamped to >= 0 for portrait decks where a thumbnail is taller than the panel.
    // Both panels use this same value so their bottom spacing matches. It resolves per
    // scroll container via container-query units; the panels set `container-type: size`.
    <div
      className={clsx(
        'grid h-svh grid-rows-[auto_1fr_auto]',
        listOpen ? 'grid-cols-2' : 'grid-cols-1',
        '[--scroll-tail:max(0px,calc(100cqh_-_100cqw/var(--slide-aspect)_+_19.5px_-_0.25rem))]',
      )}
      // React's CSSProperties has no room for custom properties, so the cast is
      // the only way to hand one to the style attribute.
      style={{ '--slide-aspect': slideAspect } as CSSProperties}
    >
      <div className="col-span-full flex flex-wrap items-center gap-3 border-b border-gray-200 bg-gray-50 px-4 py-1">
        {titleArea}
        <TooltipTrigger>
          {/* Hash-only href: it carries no path, so it keeps working under a
              subdirectory. The named target is what makes the slideshow reuse
              its own window rather than pile up new ones. */}
          <Link
            href={`#/slideshow/${activeSlide}`}
            target="nfp-slideshow"
            aria-label={m.open_slideshow_button_label()}
            className={TOOLBAR_BUTTON}
          >
            <PlayIcon size="1.25em" weight="duotone" />
          </Link>
          <Tooltip>{m.open_slideshow_button_label()}</Tooltip>
        </TooltipTrigger>
        <TooltipTrigger>
          {/* aria-expanded, not aria-pressed: this shows and hides an adjacent
              section, which WAI-ARIA calls a disclosure. `aria-pressed` would
              claim it is a setting like "bold". */}
          <Button
            aria-expanded={listOpen}
            aria-label={m.toggle_slide_list_button_label()}
            onPress={() => {
              setListOpen(!listOpen);
            }}
            className={TOOLBAR_BUTTON}
          >
            <SidebarSimpleIcon size="1.25em" weight={listOpen ? 'duotone' : 'regular'} mirrored />
          </Button>
          <Tooltip>{m.toggle_slide_list_button_label()}</Tooltip>
        </TooltipTrigger>
      </div>

      <div className="[container-type:size] relative scroll-pt-4 overflow-auto overscroll-none">
        {status === 'error' ? <ErrorOverlay message={m.outline_load_failed_status()} /> : outliner}
      </div>

      {listOpen && (
        // Scrolling and padding belong to the ListBox inside (§5.2); what stays
        // here is the panel's chrome and its `container-type: size`, which
        // --scroll-tail queries and ErrorOverlay's `absolute inset-0` positions
        // against.
        <div className="[container-type:size] border-l border-gray-200 bg-gray-50">
          {slidePanel()}
        </div>
      )}

      <div className="col-span-full flex border-t border-gray-200 bg-gray-50 px-4 py-1">
        <RadioGroup
          aria-label={m.theme_group_label()}
          // RAC defaults to vertical, which would have the group announce an
          // axis its own row layout contradicts.
          orientation="horizontal"
          value={theme}
          // RAC hands back the raw string; the group's values are exactly the
          // three modes, so narrowing it here is safe.
          onChange={(value) => {
            setTheme(value as ThemeMode);
          }}
          className="ml-auto flex gap-3"
        >
          {THEME_OPTIONS.map(({ mode, label }) => (
            <Radio
              key={mode}
              value={mode}
              className="-mx-1 flex items-center gap-1 p-1 text-sm text-gray-800"
            >
              {({ isSelected, isFocusVisible }) => (
                <>
                  {/* RAC hides the native input, so the dot is ours to draw. The
                      selected state thickens the ring into a filled centre. */}
                  <span
                    className={clsx(
                      'size-3 rounded-full border',
                      isSelected ? 'border-4 border-blue-600' : 'border-gray-500',
                      isFocusVisible && '[outline:auto] [outline:auto_-webkit-focus-ring-color]',
                    )}
                  />
                  {label()}
                </>
              )}
            </Radio>
          ))}
        </RadioGroup>
      </div>
    </div>
  );
}
