// packages/client/src/routes/slideshow/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { ActiveSlideStore } from "$lib/active-slide/active-slide-store.svelte";
    import { m } from "$lib/paraglide/messages";
    import SlideImage from "$lib/slide-image/SlideImage.svelte";
    import SlideshowFallback from "$lib/slide-status/SlideshowFallback.svelte";
    import type { DbV1 } from "$lib/dbSchema";
    import { api } from "$lib/server-client";
    import { computeSlideOverflow } from "$lib/slide-overflow";
    import { SlidesMetaStore } from "$lib/slides-meta/slides-meta-store.svelte";
    import { SyncSubscriber } from "$lib/sync/sync-subscriber";

    const meta = new SlidesMetaStore();
    let title: string = $state("");
    const active = new ActiveSlideStore();
    const sub = new SyncSubscriber();

    let syncedPageCount: number = $state(0);

    const pageCount = $derived(
        meta.data?.kind === "resolved" ? meta.data.pageCount : 0,
    );
    const hash = $derived(
        meta.data?.kind === "resolved" ? meta.data.hash : null,
    );
    // The workspace publishes a page count that already accounts for note groups
    // past the PDF's last page, so the slideshow can be asked to navigate further
    // than its own meta reports.
    const overflow = $derived(computeSlideOverflow(pageCount, syncedPageCount));

    const fallbackMessage = $derived.by(() => {
        const d = meta.data;
        switch (true) {
            case !!hash && active.value >= overflow.overflowStart:
                return m.overflow_label({ n: active.value });
            case d?.kind === "no-config-no-file":
                return m.info_no_slides();
            case d?.kind === "configured-but-missing":
                return m.error_slides_not_found({
                    path: d.configuredPath,
                });
            case d?.kind === "no-config-multiple-files":
                return m.error_multiple_pdfs({
                    files: d.candidates.join(", "),
                });
            case !!meta.error:
                return meta.error;
            default:
                return null;
        }
    });

    function step(delta: number) {
        const target = Math.min(
            overflow.slideCount,
            Math.max(1, active.value + delta),
        );
        if (target !== active.value) active.set(target);
    }

    function onKey(e: KeyboardEvent) {
        switch (e.key) {
            case "ArrowRight":
            case "ArrowDown":
            case "PageDown":
                step(1);
                break;
            case " ":
                step(e.shiftKey ? -1 : 1);
                break;
            case "ArrowLeft":
            case "ArrowUp":
            case "PageUp":
                step(-1);
                break;
            case "Home":
                if (active.value !== 1) active.set(1);
                break;
            case "End":
                if (
                    overflow.slideCount &&
                    active.value !== overflow.slideCount
                )
                    active.set(overflow.slideCount);
                break;
            default:
                return;
        }
        e.preventDefault();
    }

    function onAdvanceClick() {
        step(1);
    }

    onMount(() => {
        active.hydrate();
        void meta.load();
        void api("/nfp-data/db.json").then((db) => {
            title = (db as DbV1).title;
        });
        const stop = sub.subscribe((msg) => {
            switch (msg.type) {
                case "active-slide":
                    active.set(msg.slide);
                    break;
                case "page-count":
                    syncedPageCount = msg.count;
                    break;
            }
        });
        return () => {
            stop();
            sub.destroy();
        };
    });

    $effect(() => {
        active.syncToUrl();
    });
</script>

<svelte:head>
    <title>{title}</title>
</svelte:head>

<svelte:window onkeydown={onKey} />
<svelte:body onclick={onAdvanceClick} />

<div class="h-svh bg-black">
    {#if hash && active.value < overflow.overflowStart}
        <SlideImage {hash} slide={active.value} alt={`Slide ${active.value}`} />
    {:else if fallbackMessage}
        <SlideshowFallback message={fallbackMessage} />
    {/if}
</div>

// packages/client/src/pages/Slideshow.tsx
/**
 * Slideshow page (`/slideshow`, or `#/slideshow` in hash mode) — the full-bleed
 * slide view opened in a second window and driven over BroadcastChannel.
 *
 * Its own document, always: the workspace opens it with `target="nfp-slideshow"`
 * and there is no way back, which is why the two pages share no state and no
 * cache.
 */
import { useEffect, useEffectEvent, useState } from 'react';
import { useActiveSlide } from '../lib/routes';
import { computeSlideOverflow, stepSlide } from '../components/slides/overflow';
import { SlideImage } from '../components/slides/SlideImage';
import { describeSlidesMeta, useSlidesMeta } from '../components/slides/slidesMeta';
import { useSyncSubscriber } from '../components/slides/sync';
import { useReadOnlyDb } from '../components/workspace/db';
import { m } from '../lib/paraglide/messages.js';

export default function Slideshow() {
  const meta = useSlidesMeta();
  // Only for the window's title, and read-only in the literal sense: the
  // slideshow has nothing to save, in either mode. The ownership split gives
  // this page only meta/activeSlide/subscribe, so this fetch is a
  // deliberate addition to it — dropping it would leave the slideshow window
  // nameless, and main.tsx already warms the request for both pages.
  const db = useReadOnlyDb();
  const [activeSlide, setActiveSlide] = useActiveSlide();
  const [syncedSlideCount, setSyncedSlideCount] = useState(0);

  // Receive-only. The workspace never listens, so nothing done here travels back.
  useSyncSubscriber((message) => {
    switch (message.type) {
      case 'active-slide':
        setActiveSlide(message.slide);
        break;
      case 'slide-count':
        setSyncedSlideCount(message.count);
        break;
    }
  });

  const resolved = meta.data?.kind === 'resolved' ? meta.data : null;
  // The count on the wire already accounts for note groups past the PDF's last
  // page, so this window can be asked to navigate further than its own meta
  // reports.
  const overflow = computeSlideOverflow(resolved?.pageCount ?? 0, syncedSlideCount);

  // The presentation's own title, verbatim — not the workspace's "Presenter: …",
  // because this window is the presentation. Left alone until the document
  // lands, so the tab keeps index.html's title until there is something truer to
  // say.
  const title = db.status === 'ready' ? db.data.title : null;
  useEffect(() => {
    if (title !== null) document.title = title;
  }, [title]);

  function step(delta: number) {
    // No guard against setting the slide it is already on: React drops a state
    // update to the same value, so the clamp at either end is already a no-op.
    setActiveSlide(stepSlide(overflow, activeSlide, delta));
  }

  // Every key that could mean "next" or "previous" is bound, matching how a
  // remote presenter's forward button reports itself. On window rather than a
  // focusable element: there is nothing here to focus.
  const handleKeyDown = useEffectEvent((event: KeyboardEvent) => {
    switch (event.key) {
      case 'ArrowRight':
      case 'ArrowDown':
      case 'PageDown':
        step(1);
        break;
      case ' ':
        step(event.shiftKey ? -1 : 1);
        break;
      case 'ArrowLeft':
      case 'ArrowUp':
      case 'PageUp':
        step(-1);
        break;
      case 'Home':
        setActiveSlide(1);
        break;
      case 'End':
        // Nothing to jump to before the deck's length is known.
        if (overflow.slideCount) setActiveSlide(overflow.slideCount);
        break;
      default:
        return;
    }
    event.preventDefault();
  });

  useEffect(() => {
    const listener = (event: KeyboardEvent) => {
      handleKeyDown(event);
    };
    window.addEventListener('keydown', listener);
    return () => {
      window.removeEventListener('keydown', listener);
    };
  }, []);

  const overflowing = activeSlide >= overflow.overflowStart;
  // Overflow is decided here rather than in `describeSlidesMeta`: it depends on
  // which slide is showing, which is this page's business, and it applies even
  // though the deck resolved. Everything else is the sentence the
  // workspace's slide panel would have shown, minus the tone — a black field has
  // nothing to say a hint apart from an error with.
  const fallbackMessage =
    resolved && overflowing
      ? m.slide_beyond_pdf_pages_label({ n: activeSlide })
      : (describeSlidesMeta(meta.data, meta.error)?.message ?? null);

  return (
    // Click anywhere to advance, the way a slide remote's single button behaves.
    // The keyboard path is the window listener above, not this element.
    <div
      className="h-svh bg-black"
      onClick={() => {
        step(1);
      }}
    >
      {resolved && !overflowing ? (
        <SlideImage hash={resolved.hash} slide={activeSlide} />
      ) : (
        fallbackMessage !== null && (
          // The former SlideshowFallback, inlined: one caller.
          <div className="grid h-full place-items-center p-8 text-center font-sans text-[1.25rem] text-white">
            {fallbackMessage}
          </div>
        )
      )}
    </div>
  );
}
